name: multi_select_form_field
description: Multi Select that uses Flutter's Form Field and Decoration
version: 0.0.1
homepage: https://github.com/LeonardoJRibeiro/multi_select_form_field

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
